<!-- This code was generated by Builder.io -->
<script lang="ts">
  import Flatpickr from 'svelte-flatpickr';
  import 'flatpickr/dist/flatpickr.css';
	import Button from '../ui/Button.svelte';
  let birthdate: string = "";

  function handleSubmit() {
    console.log("Calculating for birthdate:", birthdate);
  }
</script>

<section
  class="flex flex-col items-center px-3 pt-3.5 pb-7 max-w-full text-center bg-stone-50"
>
  <h2 class="text-2xl text-black">生年月日を入れてね</h2>
  <form
    on:submit|preventDefault="{handleSubmit}"
    class="flex flex-col items-center w-full"
  >
    <label for="birthdate" class="sr-only">生年月日</label>
    <Flatpickr
      id="birthdate"
      class="flex mt-4 max-w-full bg-white border-2 border-solid border-neutral-500 text-lg p-3 text-center"
      bind:value={birthdate}
    />
    <Button
      type="button"
      onClick={handleSubmit}
    >
      <span class="text-2xl px-10 py-3 rounded-3xl max-md:px-7">
        計算する
      </span>
    </Button>
  </form>
</section>
