<!-- This code was generated by Builder.io -->
<script lang="ts">
  let birthdate: string = "";

  function handleSubmit() {
    // Implement calculation logic here
    console.log("Calculating for birthdate:", birthdate);
  }
</script>

<section
  class="flex flex-col items-center px-3 pt-3.5 pb-7 max-w-full text-center bg-stone-50 min-h-[162px] w-[265px]"
>
  <h2 class="text-base text-black">生年月日を入れてね</h2>
  <form
    on:submit|preventDefault="{handleSubmit}"
    class="flex flex-col items-center w-full"
  >
    <label for="birthdate" class="sr-only">生年月日</label>
    <input
      type="date"
      id="birthdate"
      bind:value="{birthdate}"
      class="flex mt-4 max-w-full bg-white border-2 border-solid border-neutral-500 min-h-[39px] w-[193px]"
    />
    <button
      type="submit"
      class="flex flex-col mt-4 text-xs text-white w-[94px]"
    >
      <span class="px-2.5 py-3 bg-blue-600 rounded-3xl max-md:px-5">
        計算する
      </span>
    </button>
  </form>
</section>
