/**
 * This code was generated by Builder.io.
 */
import { render, fireEvent } from "@testing-library/svelte";
import { expect, test, vi } from "vitest";
import Calculator from "./Calculator.svelte";

test("renders Calculator component with input and button", async () => {
  const { getByLabelText, getByText } = render(Calculator);
  const input = getByLabelText("生年月日");
  const button = getByText("計算する");

  expect(input).toBeTruthy();
  expect(button).toBeTruthy();

  await fireEvent.input(input, { target: { value: "1990-01-01" } });
  await fireEvent.click(button);

  // Add assertions for the calculation logic once implemented
});
