/**
 * This code was generated by Builder.io.
 */
import { render } from "@testing-library/svelte";
import { expect, test } from "vitest";
import Header from "./Header.svelte";

test("renders Header component with correct menu items", () => {
  const { getByText } = render(Header);
  expect(getByText("数秘術ってなに？")).toBeTruthy();
  expect(getByText("計算する")).toBeTruthy();
  expect(getByText("調べる")).toBeTruthy();
});
