/**
 * This code was generated by Builder.io.
 */
import { render } from "@testing-library/svelte";
import { expect, test } from "vitest";
import NumberGrid from "./NumberGrid.svelte";

test("renders NumberGrid component with all numbers", () => {
  const { getAllByText } = render(NumberGrid);
  const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  numbers.forEach((number) => {
    expect(getAllByText(`${number}番`)).toBeTruthy();
  });
});
