<!-- This code was generated by Builder.io -->
<script lang="ts">
  const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];
</script>

<section
  class="flex flex-wrap gap-11 justify-center items-center px-60 py-12 w-full text-2xl text-center text-indigo-900 bg-gray-200 max-w-[1030px] min-h-[338px] max-md:px-5 max-md:max-w-full"
>
  {#each numbers as number}
  <div
    class="flex relative grow shrink gap-2.5 justify-center items-start self-stretch px-9 py-4 my-auto min-h-[53px] shadow-[2px_4px_4px_rgba(0,0,0,0.25)] w-[120px] max-md:px-5"
  >
    <div
      class="flex absolute right-0 bottom-0 z-0 shrink-0 self-start bg-fuchsia-100 h-[53px] rounded-[29px] w-[150px]"
    ></div>
    <div class="z-0 my-auto w-[70px]">{number}番</div>
  </div>
  {/each}
</section>
